### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by salmomascarenhas** [salmomascarenhas/api-covid-daily-cases#1]
## Configurações

- [x] Implements migrations.

## Obrigatórios

- [x] `[GET]/`: Retornar um Status: 200 e uma Mensagem "Backend Challenge 2021 🏅 - Covid Daily Cases";
- [x] * `[GET]/cases/:date/count`: Listar todos os registros da base de dados no dia selecionado, agrupados por país e separados por variante;
- [x] * `[GET]/cases/:date/cumulative`: Listar todos os registros da base de dados, retornando a soma dos casos registrados de acordo desde o início do dataset até a data selecionada, agrupados por país e separados por variante;
- [x] `[GET]/dates`: Listar as datas disponíveis no dataset;
- [x] Script para armazenar os dados do arquivo CSV;

## Diferenciais
- [x] Configurar Docker no Projeto para facilitar o Deploy da equipe de DevOps;
- [ ] Escrever Unit Tests para os endpoints da API;
- [x] Descrever a documentação da API utilizando o conceito de Open API 3.0;
- [ ] Usar a [Kaggle API](https://github.com/Kaggle/kaggle-api) para baixar os arquivos do dataset. Lembrando que esta biblioteca roda com Python, então será necessário conferir se o ambiente pode executar a biblioteca;Usar a [Kaggle API](https://github.com/Kaggle/kaggle-api) para baixar os arquivos do dataset. Lembrando que esta biblioteca roda com Python, então será necessário conferir se o ambiente pode executar a biblioteca;
- [x] Salvar em cache o resultado dos endpoints, para agilizar a resposta em caso de buscas com parâmetros repetidos;
- [ ] Utilizar aggregate para calcular os dados cumulativos;
- [ ] Publique o projeto em alguma plataforma, como por exemplo a [Heroku](https://heroku.com/), [Glitch](https://www.glitch.com/) ou outra de sua preferência.Publique o projeto em alguma plataforma, como por exemplo a [Heroku](https://heroku.com/), [Glitch](https://www.glitch.com/) ou outra de sua preferência.

## Readme do Repositório
- [x] Deve conter o título do projeto;
- [x] Uma descrição em frase;
- [x] Conter uma lista com linguagem, framework e/ou tecnologias usadas.
- [x] Instruções de como instar e usar o projeto;
- [x] Ter gitignore;
- [x] Referência ao challenge by coodesh.
